export enum EventType {
  TASK_CREATED = 'TASK_CREATED',
  TASK_ASSIGNED = 'TASK_ASSIGNED',
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETED = 'TASK_COMPLETED',
  MAP_FEATURE_EXTRACTED = 'MAP_FEATURE_EXTRACTED',
  QA_RESULT = 'QA_RESULT',
  RISK_ASSESSMENT = 'RISK_ASSESSMENT',
  OPERATIONS_ALERT = 'OPERATIONS_ALERT',
  REPORT_GENERATED = 'REPORT_GENERATED',
  AUDIT_LOGGED = 'AUDIT_LOGGED',
  WORKFLOW_ESCALATED = 'WORKFLOW_ESCALATED',
  APPROVAL_GRANTED = 'APPROVAL_GRANTED',
  APPROVAL_REJECTED = 'APPROVAL_REJECTED',
  MAP_UPDATE = 'MAP_UPDATE'
}

export interface BandEventPayload {
  type: EventType;
  timestamp: string;
  sourceAgent: string;
  correlationId: string;
  data: any;
}
